### ISSUE TITLE
Does it work on macOS or Linux?

### ISSUE THREAD

**Issue by oliverschwendener** [FlurinBruehwiler/flamui#16]
Hello there, I just found this interesting project and I wanted to try it out on my macOS computer. I followed the basic hello world example, but I couldn't run the app. Is it expected to work on macOS or Linux currently, or is this Windows-only right now?

**Comment by FlurinBruehwiler** [comment]
Glad you are interested in the project, I'm a daily user of ueli! As to your question, I haven't tested it on MacOS as I don't have a mac. I once tried it on Linux, but I don't regularly test on it. So yes, right now, its kinda Windows-Only but the architecture should allow for easy portability to other platforms. I have currently a lot of other things going on, so the development is paused for a bit.   Also, [this](https://www.pangui.io/) project got announced recently and it has a similar approach to flamui while seeming like the more polished version. So I'm also looking where it goes to decide what the future of my project looks like.

**Comment by oliverschwendener** [comment]
Nice, great to hear :) Alright, thanks for your response. Keep it up!
